
name: Build test deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install NPM modules
      run: npm install
    - name: Start Backend
      run: npm run start-be &
    - name: Start Frontend
      run: npm run start-fe &
    - name: Execute UI tests
      run: npm run test:ui
    
